server:
  port: 8080

info:
  app:
    name: '@project.name@'
    version: '@project.version@-0'
    description: '@project.description@'

spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: never
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048